FROM node:20.10 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20.10

WORKDIR /app
ENV NODE_ENV='production'

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./

# EXPOSE 3000

CMD ["node", "dist/main"]